-- 3세대 대장균의 ID
-- ID 오름차순

-- 1, 2가 1세대 -> parent 없음
-- 3, 4, 5 -> 2세대 -> parent가 null
WITH PARENT_TOTAL AS
(SELECT
    PARENT.ID, PARENT.PARENT_ID
FROM ECOLI_DATA PARENT
LEFT OUTER JOIN ECOLI_DATA CHILD
ON PARENT.ID = CHILD.PARENT_ID)

SELECT
    PT_ID AS ID
FROM PARENT_TOTAL P3
RIGHT OUTER JOIN 
(SELECT PT.ID PT_ID, PT.PARENT_ID AS PT_PARENT_ID,
    P2.ID P2_ID, P2.PARENT_ID AS P2_PARENT_ID
FROM PARENT_TOTAL PT
JOIN PARENT_TOTAL P2
ON PT.PARENT_ID = P2.ID)P4
ON P3.ID = P4.P2_PARENT_ID
WHERE ID IS NOT NULL AND PARENT_ID IS NULL
GROUP BY PT_ID
ORDER BY ID ASC


# PARENT.PARENT_ID = null이면 -> 1세대
# PARENT.PARENT_ID 가 null이 아니면 일단 세대
# PARENT.PARENT_ID = PARENT.ID 만나는 곳에서의 PARENT_ID가 null이면 2세대
-- 2번 확인하면 3세대
# PARENT.ID = PARENT.PARENT_ID -> PARENT.PARENT_ID 를 확인