WITH PARENT AS
(SELECT A.ITEM_ID AS ITEM_ID,
        A.ITEM_NAME AS ITEM_NAME,
        A.RARITY AS RARITY,
        B.PARENT_ITEM_ID AS PARENT_ITEM_ID
    FROM ITEM_INFO A
    JOIN ITEM_TREE B
        ON A.ITEM_ID = B.ITEM_ID)

SELECT 
    P.ITEM_ID, P.ITEM_NAME, P.RARITY
FROM 
    PARENT P 
JOIN
    (SELECT CHILD.ITEM_ID FROM PARENT 
    RIGHT OUTER JOIN ITEM_TREE CHILD
        ON PARENT.PARENT_ITEM_ID = CHILD.ITEM_ID
    WHERE PARENT.PARENT_ITEM_ID IS NULL)C
    ON P.ITEM_ID = C.ITEM_ID
ORDER BY P.ITEM_ID DESC;