SELECT 
    USER.USER_ID AS USER_ID,
    USER.NICKNAME AS NICKNAME,
    CONCAT(USER.CITY, ' ', USER.STREET_ADDRESS1, ' ', USER.STREET_ADDRESS2) AS '전체주소',
    -- 전화번호
    CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8)) AS '전화번호'
    
FROM
    (SELECT WRITER_ID, COUNT(*) AS CNT
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING CNT >= 3)GOODS
JOIN USED_GOODS_USER USER
    ON GOODS.WRITER_ID = USER.USER_ID
ORDER BY USER_ID DESC
