SELECT 
    A.ROUTE AS ROUTE,
    CONCAT(A.TOTAL_DISTANCE, 'km') AS TOTAL_DISTANCE, 
    CONCAT(A.AVERAGE_DISTANCE, 'km') AS AVERAGE_DISTANCE
FROM
    (SELECT
        ROUTE,
        ROUND(SUM(D_BETWEEN_DIST), 1) AS TOTAL_DISTANCE, 
        ROUND(AVG(D_BETWEEN_DIST), 2) AS AVERAGE_DISTANCE
    FROM SUBWAY_DISTANCE
    GROUP BY(ROUTE)
    ORDER BY TOTAL_DISTANCE DESC)A;