SELECT
    COUNT(*) AS FISH_COUNT,
    F_NAME.FISH_NAME AS FISH_NAME
FROM FISH_NAME_INFO F_NAME
JOIN FISH_INFO F_INFO
ON F_NAME.FISH_TYPE = F_INFO.FISH_TYPE
GROUP BY (F_NAME.FISH_NAME)
ORDER BY FISH_COUNT DESC;