SELECT 
    MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM
(SELECT
        MONTH(START_DATE) AS MONTH,
        CAR_ID,
        COUNT(CAR_ID) OVER (PARTITION BY CAR_ID) AS TOTAL_RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10')A
WHERE TOTAL_RECORDS >= 5
GROUP BY CAR_ID, MONTH
ORDER BY MONTH ASC, CAR_ID DESC;