-- 물고기 정보를 합친 테이블
WITH FISH_TOTAL AS (
SELECT ID, A.FISH_TYPE AS FISH_TYPE, 
    B.FISH_NAME AS FISH_NAME, 
    A.LENGTH AS LENGTH, 
    A.TIME
FROM FISH_INFO A
    LEFT OUTER JOIN FISH_NAME_INFO B
        ON A.FISH_TYPE = B.FISH_TYPE
)

SELECT 
    A.ID AS ID, B.FISH_NAME AS FISH_NAME, B.LENGTH AS LENGTH
FROM FISH_TOTAL A
JOIN (SELECT FISH_NAME, MAX(LENGTH) AS LENGTH
        FROM FISH_TOTAL
        GROUP BY (FISH_NAME))B
    ON A.FISH_NAME = B.FISH_NAME AND A.LENGTH = B.LENGTH
ORDER BY ID ASC;
