SELECT
    SUM(SCORE) AS SCORE,
    HR_E.EMP_NO AS EMP_NO,
    HR_E.EMP_NAME AS EMP_NAME,
    HR_E.POSITION AS POSITION,
    HR_E.EMAIL AS EMAIL
FROM HR_EMPLOYEES HR_E
JOIN HR_GRADE HR_G
ON HR_E.EMP_NO = HR_G.EMP_NO
WHERE HR_G.YEAR = 2022
GROUP BY (HR_G.EMP_NO)
ORDER BY SCORE DESC
LIMIT 1;

