WITH PRE AS(
SELECT FISH_TYPE, IFNULL(LENGTH,10) AS LENGTH FROM FISH_INFO)

SELECT COUNT(*) AS FISH_COUNT, 
    MAX(LENGTH) AS MAX_LENGTH, 
    FISH_TYPE AS FISH_TYPE 
FROM PRE
GROUP BY FISH_TYPE
HAVING AVG(LENGTH)>(33)
ORDER BY FISH_TYPE ASC